import { ShieldAlert } from "lucide-react";

export function ShadowAI() {

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight flex items-center">
            <ShieldAlert className="mr-2 h-6 w-6 text-destructive" />
            Shadow AI Inbox
          </h2>
          <p className="text-muted-foreground mt-1">
            Activity generated by unregistered or unknown processes that exhibit AI-like behavior.
          </p>
        </div>
      </div>

      <div className="glass rounded-xl p-6">
        <h3 className="font-semibold mb-4">Unregistered Activity</h3>
        <div className="flex h-[200px] items-center justify-center rounded-md border border-dashed border-muted">
          <p className="text-sm text-muted-foreground">
            No shadow AI activity detected.
          </p>
        </div>
      </div>
    </div>
  );
}
