import { useState, useEffect } from "react";
import { ShieldAlert, AlertTriangle } from "lucide-react";
import { RegistryApi } from "../services/api";
import { RegisterControlBar } from "../components/RegisterControlBar";

export function ShadowAI({ hideHeader = false }: { hideHeader?: boolean }) {
  const [candidates, setCandidates] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    RegistryApi.listDiscoveryCandidates()
      .then(setCandidates)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6">
      {!hideHeader && (
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold tracking-tight flex items-center">
              <ShieldAlert className="mr-2 h-6 w-6 text-destructive" />
              Shadow AI Inbox
            </h2>
            <p className="text-muted-foreground mt-1">
              Activity generated by unregistered or unknown processes that
              exhibit AI-like behavior.
            </p>
          </div>
        </div>
      )}

      <div className="glass rounded-lg p-4">
        <h3 className="font-semibold mb-4">Unregistered Activity</h3>
        {loading ? (
          <div className="flex h-[200px] items-center justify-center rounded-md border border-dashed border-muted">
            <p className="text-sm text-muted-foreground">
              Loading shadow candidates...
            </p>
          </div>
        ) : candidates.length === 0 ? (
          <div className="flex h-[200px] items-center justify-center rounded-md border border-dashed border-muted">
            <p className="text-sm text-muted-foreground">
              No shadow AI activity detected.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {candidates.map((c, idx) => (
              <div
                key={idx}
                className="border rounded-lg p-4 bg-destructive/5 hover:bg-destructive/10 transition-colors"
              >
                <div className="flex justify-between items-start mb-2">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="h-5 w-5 text-destructive" />
                    <h4 className="font-medium text-lg">
                      {c.display_name || "Unknown Agent Activity"}{" "}
                      {c.inferred_agent_type && (
                        <span className="text-xs text-muted-foreground font-normal">
                          ({c.inferred_agent_type})
                        </span>
                      )}
                    </h4>
                  </div>
                  <RegisterControlBar
                    agentId={c.candidate_id}
                    tenantId="local"
                    onSuccess={() => window.location.reload()}
                  />
                </div>
                <div className="space-y-1">
                  <p className="text-muted-foreground text-sm font-mono bg-muted/20 inline-block px-2 py-0.5 rounded border mb-2">
                    ID: {c.candidate_id}
                  </p>
                  <p className="text-muted-foreground text-sm">
                    <span className="font-medium">First seen:</span>{" "}
                    {new Date(c.first_seen).toLocaleString()} <br />
                    <span className="font-medium">Last seen:</span>{" "}
                    {new Date(c.last_seen).toLocaleString()}
                  </p>
                  {c.heuristics_matched && c.heuristics_matched.length > 0 && (
                    <div className="mt-2 pt-2 border-t border-destructive/10">
                      <p className="text-sm font-medium mb-1">
                        Suspicious Heuristics Detected:
                      </p>
                      <ul className="list-disc pl-5 text-xs text-muted-foreground">
                        {c.heuristics_matched.map((h: string, i: number) => (
                          <li key={i}>{h.replace(/_/g, " ")}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {c.evidence && c.evidence.length > 0 && (
                    <div className="mt-2 text-xs text-muted-foreground">
                      <span className="font-medium">Evidence Sources:</span>{" "}
                      {c.evidence.map((e: any) => e.source).join(", ")}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
