#pragma once

#define FILE_DEVICE_POLLEN_DEK_WFP 0x8337

#define IOCTL_POLLEN_WFP_SET_POLICY_VERSION CTL_CODE( \
    FILE_DEVICE_POLLEN_DEK_WFP, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_POLLEN_WFP_ADD_DECISION CTL_CODE( \
    FILE_DEVICE_POLLEN_DEK_WFP, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_POLLEN_WFP_CLEAR_CACHE CTL_CODE( \
    FILE_DEVICE_POLLEN_DEK_WFP, 0x803, METHOD_BUFFERED, FILE_WRITE_DATA)

typedef struct _POLLEN_USER_DECISION {
    UINT64 PolicyVersion;
    UINT8  Direction;
    UINT8  IpVersion;
    UINT8  Protocol;
    UINT16 LocalPort;
    UINT16 RemotePort;
    UINT32 LocalAddrV4;
    UINT32 RemoteAddrV4;
    UINT64 ProcessId;
    UINT8  Action;
    UINT32 TtlSeconds;
} POLLEN_USER_DECISION;
