CREATE TABLE IF NOT EXISTS ai_usage_events (
    event_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    event_kind TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    received_at TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT,
    device_id TEXT,
    actor_id_hash TEXT,
    actor_kind TEXT,
    trace_id TEXT NOT NULL,
    span_id TEXT NOT NULL,
    parent_span_id TEXT,
    session_id TEXT,
    task_id TEXT,
    agent_run_id TEXT,
    agent_step_id TEXT,
    invocation_id TEXT,
    agent_id TEXT,
    agent_instance_id TEXT,
    agent_type TEXT NOT NULL,
    parent_agent_id TEXT,
    subagent_id TEXT,
    shadow_candidate_id TEXT,
    provider TEXT,
    provider_api TEXT,
    provider_request_id TEXT,
    model TEXT,
    model_version TEXT,
    service_tier TEXT,
    inference_region TEXT,
    surface TEXT NOT NULL,
    pep_type TEXT,
    control_mode TEXT,
    policy_ids_json TEXT NOT NULL DEFAULT '[]',
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER NOT NULL DEFAULT 0,
    cached_input_tokens INTEGER NOT NULL DEFAULT 0,
    cache_write_input_tokens INTEGER NOT NULL DEFAULT 0,
    reasoning_output_tokens INTEGER NOT NULL DEFAULT 0,
    tool_prompt_tokens INTEGER NOT NULL DEFAULT 0,
    tool_result_tokens INTEGER NOT NULL DEFAULT 0,
    image_input_tokens INTEGER NOT NULL DEFAULT 0,
    image_output_tokens INTEGER NOT NULL DEFAULT 0,
    audio_input_tokens INTEGER NOT NULL DEFAULT 0,
    audio_output_tokens INTEGER NOT NULL DEFAULT 0,
    usage_source TEXT NOT NULL,
    usage_estimated INTEGER NOT NULL DEFAULT 0,
    usage_details_json TEXT NOT NULL DEFAULT '{}',
    currency TEXT NOT NULL DEFAULT 'USD',
    input_cost REAL NOT NULL DEFAULT 0,
    output_cost REAL NOT NULL DEFAULT 0,
    cached_input_cost REAL NOT NULL DEFAULT 0,
    cache_write_input_cost REAL NOT NULL DEFAULT 0,
    reasoning_output_cost REAL NOT NULL DEFAULT 0,
    tool_cost REAL NOT NULL DEFAULT 0,
    image_cost REAL NOT NULL DEFAULT 0,
    audio_cost REAL NOT NULL DEFAULT 0,
    total_cost REAL NOT NULL DEFAULT 0,
    price_catalog_version TEXT,
    pricing_tier_id TEXT,
    cost_source TEXT NOT NULL,
    cost_estimated INTEGER NOT NULL DEFAULT 1,
    cost_details_json TEXT NOT NULL DEFAULT '{}',
    tool_id TEXT,
    tool_name TEXT,
    mcp_server_id TEXT,
    resource_id TEXT,
    resource_type TEXT,
    latency_ms INTEGER,
    status TEXT NOT NULL,
    error_code TEXT,
    provider_usage_raw_json TEXT NOT NULL DEFAULT '{}',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    event_json TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    cloud_sync_status TEXT NOT NULL DEFAULT 'pending',
    local_sequence INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_tenant_time ON ai_usage_events(tenant_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_agent_time ON ai_usage_events(tenant_id, agent_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_trace ON ai_usage_events(trace_id, span_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_provider_model ON ai_usage_events(tenant_id, provider, model, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_task ON ai_usage_events(tenant_id, task_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_session ON ai_usage_events(tenant_id, session_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_surface ON ai_usage_events(tenant_id, surface, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_sync ON ai_usage_events(cloud_sync_status, created_at);

CREATE TABLE IF NOT EXISTS ai_usage_rollups (
    bucket_start TEXT NOT NULL,
    bucket_size TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT,
    device_id TEXT,
    agent_id TEXT,
    agent_id_key TEXT NOT NULL DEFAULT '',
    agent_type TEXT,
    provider TEXT,
    provider_key TEXT NOT NULL DEFAULT '',
    model TEXT,
    model_key TEXT NOT NULL DEFAULT '',
    surface TEXT,
    surface_key TEXT NOT NULL DEFAULT '',
    tool_id TEXT,
    tool_id_key TEXT NOT NULL DEFAULT '',
    resource_id TEXT,
    resource_id_key TEXT NOT NULL DEFAULT '',
    request_count INTEGER NOT NULL DEFAULT 0,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER NOT NULL DEFAULT 0,
    cached_input_tokens INTEGER NOT NULL DEFAULT 0,
    cache_write_input_tokens INTEGER NOT NULL DEFAULT 0,
    reasoning_output_tokens INTEGER NOT NULL DEFAULT 0,
    total_cost REAL NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    PRIMARY KEY (
        bucket_start,
        bucket_size,
        tenant_id,
        agent_id_key,
        provider_key,
        model_key,
        surface_key,
        tool_id_key,
        resource_id_key
    )
);

CREATE INDEX IF NOT EXISTS idx_ai_rollup_query ON ai_usage_rollups(tenant_id, bucket_size, bucket_start);

CREATE TABLE IF NOT EXISTS ai_budget_limits (
    budget_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    window TEXT NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    soft_cost_limit REAL,
    hard_cost_limit REAL,
    soft_token_limit INTEGER,
    hard_token_limit INTEGER,
    action_on_soft TEXT NOT NULL DEFAULT 'warn',
    action_on_hard TEXT NOT NULL DEFAULT 'deny',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_json TEXT NOT NULL,
    UNIQUE(tenant_id, scope_type, scope_id, window)
);

CREATE TABLE IF NOT EXISTS ai_budget_events (
    event_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    budget_id TEXT,
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    event_kind TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    current_cost REAL,
    current_tokens INTEGER,
    projected_cost REAL,
    projected_tokens INTEGER,
    action TEXT NOT NULL,
    related_usage_event_id TEXT,
    data_json TEXT NOT NULL DEFAULT '{}'
);
