name: Docs Validation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16
        with:
          globs: |
            docs/**/*.md
            *.md
